name: Release

on:
  push:
<<<<<<< Updated upstream
    tags:
      - 'v*'
=======
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
>>>>>>> Stashed changes

jobs:
  build:
    name: Build Release
    runs-on: macos-latest
<<<<<<< Updated upstream
    
    steps:
    - uses: actions/checkout@v4
    
=======

    steps:
    - uses: actions/checkout@v4

>>>>>>> Stashed changes
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
<<<<<<< Updated upstream
    
=======

>>>>>>> Stashed changes
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          rust-core/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
<<<<<<< Updated upstream
    
    - name: Build UniFFI bindgen
      run: make ci-build-uniffi-bindgen
    
    - name: Build release
      run: make ci-build-release
    
    - name: Create distribution package
      run: make ci-create-distribution-package
    
    - name: Create tarball
      run: make ci-create-tarball
    
=======

    - name: Build UniFFI bindgen
      run: make ci-build-uniffi-bindgen

    - name: Build release
      run: make ci-build-release

    - name: Create distribution package
      run: make ci-create-distribution-package

    - name: Create tarball
      run: make ci-create-tarball

>>>>>>> Stashed changes
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rem-tui-release
        path: dist/rem-tui-macos.tar.gz
        retention-days: 90
<<<<<<< Updated upstream
    
=======

>>>>>>> Stashed changes
    outputs:
      tarball: dist/rem-tui-macos.tar.gz

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
<<<<<<< Updated upstream
    
    steps:
    - uses: actions/checkout@v4
    
=======

    steps:
    - uses: actions/checkout@v4

>>>>>>> Stashed changes
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: rem-tui-release
        path: dist/
<<<<<<< Updated upstream
    
    - name: Extract version from tag
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
=======

    - name: Extract version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
        else
          # For push to main, use commit SHA as version
          echo "version=v$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        fi

>>>>>>> Stashed changes
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Rem TUI ${{ steps.version.outputs.version }}
        body: |
          # Rem TUI ${{ steps.version.outputs.version }}
<<<<<<< Updated upstream
          
          A fast TUI (Terminal User Interface) for Apple Reminders built with Swift and Rust.
          
          ## Installation
          
=======

          A fast TUI (Terminal User Interface) for Apple Reminders built with Swift and Rust.

          ## Installation

>>>>>>> Stashed changes
          1. Download `rem-tui-macos.tar.gz`
          2. Extract the archive: `tar -xzf rem-tui-macos.tar.gz`
          3. Move the binary to your PATH: `mv rem-tui /usr/local/bin/`
          4. Make sure the dylib is in the same directory or in your library path
<<<<<<< Updated upstream
          
          ## Requirements
          
          - macOS 14.0 or later
          - Reminders app permissions (will be requested on first run)
          
          ## Usage
          
          ```bash
          rem-tui
          ```
          
          Navigate with vim-style keys (j/k for up/down, enter to select).
          
          ## What's New
          
          See the commit history for details about changes in this release.
        files: |
          dist/rem-tui-macos.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======

          ## Requirements

          - macOS 14.0 or later
          - Reminders app permissions (will be requested on first run)

          ## Usage

          ```bash
          rem-tui
          ```

          Navigate with vim-style keys (j/k for up/down, enter to select).

          ## What's New

          ${{ github.event_name == 'workflow_dispatch' && 'Manual release triggered.' || 'Automatic release from main branch.' }}

          See the commit history for details about changes in this release.
        files: |
          dist/rem-tui-macos.tar.gz
        draft: ${{ github.event_name == 'push' }}
        prerelease: ${{ github.event_name == 'push' }}
        make_latest: ${{ github.event_name == 'workflow_dispatch' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> Stashed changes
