name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    name: Build Release
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          rust-core/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build UniFFI bindgen
      run: make ci-build-uniffi-bindgen

    - name: Build release
      run: make ci-build-release

    - name: Create distribution package
      run: make ci-create-distribution-package

    - name: Sign application (if certificates available)
      run: |
        if [ -n "${{ secrets.APPLE_CERTIFICATE_P12_BASE64 }}" ]; then
          echo "Setting up signing..."
          # Create keychain
          security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          
          # Import certificate
          echo "${{ secrets.APPLE_CERTIFICATE_P12_BASE64 }}" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          
          # Set key partition list
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          
          # Sign the dylib first
          codesign --force --deep --sign "${{ secrets.APPLE_SIGNING_IDENTITY }}" dist/librem_core.dylib
          
          # Sign the main executable
          codesign --force --deep --sign "${{ secrets.APPLE_SIGNING_IDENTITY }}" dist/rem-tui
          
          # Verify signatures
          codesign --verify --verbose dist/librem_core.dylib
          codesign --verify --verbose dist/rem-tui
          
          echo "✅ Application signed successfully"
        else
          echo "⚠️ No signing certificates configured - app will show security warning"
        fi

    - name: Create tarball
      run: make ci-create-tarball

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rem-tui-release
        path: dist/rem-tui-macos.tar.gz
        retention-days: 90
    outputs:
      tarball: dist/rem-tui-macos.tar.gz

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write  # Required for creating releases

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: rem-tui-release
        path: dist/

    - name: Extract version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
        else
          # For push to main, use commit SHA as version
          echo "version=v$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Rem TUI ${{ steps.version.outputs.version }}
        body: |
          # Rem TUI ${{ steps.version.outputs.version }}

          A fast TUI (Terminal User Interface) for Apple Reminders built with Swift and Rust.

          ## Installation

          1. Download `rem-tui-macos.tar.gz`
          2. Extract the archive: `tar -xzf rem-tui-macos.tar.gz`
          3. Move the binary to your PATH: `mv rem-tui /usr/local/bin/`
          4. Make sure the dylib is in the same directory or in your library path

          ## Requirements

          - macOS 14.0 or later
          - Reminders app permissions (will be requested on first run)

          ## Usage

          ```bash
          rem-tui
          ```

          Navigate with vim-style keys (j/k for up/down, enter to select).

          ## What's New

          ${{ github.event_name == 'workflow_dispatch' && 'Manual release triggered.' || 'Automatic release from main branch.' }}

          See the commit history for details about changes in this release.
        files: |
          dist/rem-tui-macos.tar.gz
        draft: ${{ github.event_name == 'push' }}
        prerelease: ${{ github.event_name == 'push' }}
        generate_release_notes: ${{ github.event_name == 'workflow_dispatch' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
